server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://Ayaka520:3306/springcloud-dame?useSSL=false
    username: springcloud-dame
    password: zjj3eJmm2RNcbAxH
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  # cloud配置
  cloud: # 配置 nacos 地址
    nacos:
      server-addr: localhost:8848
      discovery: # 服务分级存储模型 给该服务配置 集群
        cluster-name: Ayaka
        namespace: 492a7d5d-237b-46a1-a99a-fa8e98e4b0f9 # 命名空间，填ID
        ephemeral: false # 设置为非临时实例 默认是临时实例
# 上面并不会生效 要进行负载均衡从新配置
userservice: # 对 userservice 单独进行配置负载均衡算法
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

mybatis:
  type-aliases-package: com.ganga.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.ganga: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
