server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://ayaka520:3306/springcloud-dame?useSSL=false
    username: springcloud-dame
    password: zjj3eJmm2RNcbAxH
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ayaka520
    username: ganga
    password: password
    virtual-host: /
logging:
  level:
    com.ganga: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ganga.hotel.pojo