server:
  port: 8081
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://Ayaka520:3306/springcloud-dame?useSSL=false
    username: springcloud-dame
    password: abcdefghigklmn
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos: # 配置 nacos 地址
      server-addr: localhost:8848
      discovery: # 服务分级存储模型 给该服务配置 集群
        cluster-name: Ayaka

mybatis:
  type-aliases-package: com.ganga.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.ganga: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

